server:
  port: 8070
spring:
  application:
    name: service-provider
  cloud:
    nacos:
	  discovery:
	    server-addr: nacos-qv2kue.nacos.cse.com
      namespace: demo
	  config:
	    server-addr: nacos-qv2kue.nacos.cse.com
      namespace: demo
